apiVersion: v1
kind: Service
metadata:  
  name: staging-backend-quiz-app-server-service
  namespace: default
spec:
  type: LoadBalancer
  selector: 
    app: staging-backend-quiz-app-server-pod
  ports:
    - protocol: TCP
      port: 4100
      targetPort: 4100
  sessionAffinity: None
